questions =  [
    {"id": 1, "question": "I view the seiyuu primarily as talented artists and professionals, not as objects for my personal fantasy.", "effects": {"degenerate": -1}},
    {"id": 2, "question": "Fans who make inappropriate sexual comments about the cast on Discord or Twitter should be completely shunned by the community.", "effects": {"degenerate": -1}},
    {"id": 3, "question": "Holding more than one standard electronic penlight to a concert is completely unnecessary and excessive.", "effects": {"yakkai": -1}},
    {"id": 4, "question": "If an idol is seen in public or their private social media is found, fans have a strict moral obligation to leave them completely alone.", "effects": {"degenerate": -1}},
    {"id": 5, "question": "Jumping or vigorously waving a penlight to the beat is distracting; fans should just watch the stage quietly.", "effects": {"yakkai": -1}},
    {"id": 6, "question": "I attend lives primarily to appreciate the vocal talents, choreography, and the live band, rather than to glaze at the cast.", "effects": {"degenerate": -1}},
    {"id": 7, "question": "I would fully support my oshi if she decided to take a break for her mental or physical health, even if it meant missing a live.", "effects": {"degenerate": -1}},
    {"id": 8, "question": "Using terms like 'weak man' or 'simp' to describe oneself is degrading and sets a terrible standard for the fandom.", "effects": {"degenerate": -1}},
    {"id": 9, "question": "The best way to show support for the franchise is by buying official merchandise and music through proper channels, not obsessing over the cast's bodies.", "effects": {"degenerate": -1}},
    {"id": 10, "question": "I find it highly disrespectful when fans complain about an idol 'gaining weight' or changing her appearance.", "effects": {"degenerate": -1}},
    {"id": 11, "question": "Shouting the Standard Mix ('Tiger, Fire, Cyber, Fiber, Diver, Viber, Jyaa Jyaa!') during a Love Live song intro is a great way to hype up the crowd.", "effects": {"yakkai": 1}},
    {"id": 12, "question": "Doing excessive Wotagei movements (like the Thunder Snake or Cyclone) in a cramped arena seat is totally justified if the song goes hard.", "effects": {"yakkai": 1}},
    {"id": 13, "question": "Cracking an entire 25-pack box of UOs over the course of a single concert is normal behavior for a dedicated fan.", "effects": {"yakkai": 1}},
    {"id": 14, "question": "Screaming an idol's name at the top of my lungs while they are trying to do a quiet, emotional MC is completely acceptable.", "effects": {"yakkai": 1}},
    {"id": 15, "question": "Sneaking in a modified, excessively bright penlight that exceeds venue regulations [cite: 103] is a great idea to make my oshi notice me from the stage.", "effects": {"yakkai": 1}},
    {"id": 16, "question": "I care more about front-row arena seats to look at the performers' legs than actually hearing the live band and vocals.", "effects": {"degenerate": 1}},
    {"id": 17, "question": "Spamming the Gachikoi Koujou ('Iitai koto ga arunda yo...') directly at my oshi during a slow solo ballad is the best way to show my true love.", "effects": {"yakkai": 1, "degenerate": 1}},
    {"id": 18, "question": "The performers' personal lives are none of my business, and I don't care who they date or associate with off-stage.", "effects": {"degenerate": -1}},
    {"id": 19, "question": "Looping the buppan line to spend my entire monthly paycheck on trading bromides and gacha to complete my shrine is a healthy financial decision.", "effects": {"degenerate": 1}},
    {"id": 20, "question": "I genuinely believe my oshi is my girlfriend, and any interaction she has with male staff or cast members makes me intensely jealous.", "effects": {"degenerate": 1}},
    {"id": 21, "question": "If the music fades out into a dead-silent acoustic break, that is the perfect time to yell 'Yeah Taiga!' to get a laugh.", "effects": {"yakkai": 1}},
    {"id": 22, "question": "When a new picture of a seiyuu drops on Discord, typing a brainless 'WOOOOOOOAH' is a completely normal and appropriate response.", "effects": {"degenerate": 1}},
    {"id": 23, "question": "I regularly make comments wishing a specific idol would 'step on me' or physically/verbally abuse me.", "effects": {"degenerate": 1}},
    {"id": 24, "question": "It is perfectly fine to closely analyze and make remarks about an idol's specific body parts when discussing them online.", "effects": {"degenerate": 1}},
    {"id": 25, "question": "When discussing a live, the conversation should focus on vocal performance, choreography, and emotional delivery rather than looks.", "effects": {"degenerate": -1}},
    {"id": 26, "question": "Hyper-sexualized remarks about the performers are cringeworthy and show a deep lack of respect.", "effects": {"degenerate": -1}},
    {"id": 27, "question": "Leaving meaningful, constructive comments about a performance is far better than just spamming reaction memes and emojis.", "effects": {"degenerate": -1}},
    {"id": 28, "question": "I would genuinely be happy for a seiyuu if they announced they got married, rather than feeling betrayed or angry.", "effects": {"degenerate": -1}},
    {"id": 29, "question": "Popping a high-brightness Ultra Orange (UO) during a slow, blue-themed ballad is a fine.", "effects": {"yakkai": 1}},
    {"id": 30, "question": "Doing the cyclone (spinning glowsticks in a cartwheel motion above your head) is perfectly fine, even if the song isn't particularly hyped.", "effects": {"yakkai": 1}},
    {"id": 31, "question": "If my aggressive calling or penlight swinging annoys my renban (seat partner), that's their problem, not mine.", "effects": {"yakkai": 1}},
    {"id": 32, "question": "Going full yakkai (gachikoi koujou, 3ren kahen, UOs) in a private karaoke room with friends is an absolute necessity.", "effects": {"yakkai": 1}},
    {"id": 33, "question": "Jumping and getting sweaty at a live is exhausting; I prefer to sit or stand motionless to fully absorb the performance.", "effects": {"yakkai": -1}},
    {"id": 34, "question": "If I can’t compliment an idol without referencing their body, I should probably not comment at all.", "effects": {"degenerate": -1}},
    {"id": 35, "question": "“She’s so hot” is a low-effort comment; it’s better to talk about skills, stage presence, or personality.", "effects": {"degenerate": -1}},
    {"id": 36, "question": "It’s embarrassing when fans loudly thirst-post in front of newcomers or casual fans.", "effects": {"degenerate": -1}},
    {"id": 37, "question": "If someone asks to keep things non-horny in a server/channel, that request is reasonable.", "effects": {"degenerate": -1}},
    {"id": 38, "question": "At concerts, I prefer to keep calls minimal and focus on watching the performance.", "effects": {"yakkai": -1}},
    {"id": 39, "question": "I’m fine not jumping or moving much as long as I’m enjoying the music.", "effects": {"yakkai": -1}},
    {"id": 40, "question": "Silence is fine—if I’m not feeling a call, I simply won’t do it.", "effects": {"yakkai": -1}},
    {"id": 41, "question": "I’d rather under-react than over-react and risk bothering someone nearby.", "effects": {"yakkai": -1}},
    {"id": 42, "question": "I save controversial calls/mixes for karaoke or anikura, not for the actual Love Live venue.", "effects": {"yakkai": -1}},
    {"id": 43, "question": "Matching the venue’s color culture (member colors / song colors) is more important than showing off my own style.", "effects": {"yakkai": -1}},
    {"id": 44, "question": "Breaking UOs randomly is fine—even if the section is doing a calm color and the song isn’t a hype moment.", "effects": {"yakkai": 1}},
    {"id": 45,  "question": "I feel second-hand embarrassment when people spam ‘WOOOAAAH’ style reactions with no meaningful comment.", "effects": {"degenerate": -1}},
    {"id": 46, "question": "If a call or chant is frowned upon in Love Live concerts, doing it anyway ‘for the meme’ is still fair game.", "effects": {"yakkai": 1}},
    {"id": 47, "question": "I don't bring UOs to lives because they're wasteful, expensive, and unnecessary.", "effects": {"yakkai": -1}},
    {"id": 48, "question": "Shouting 'Ore no (oshi name)!' during a Love Live live is a perfectly acceptable way to show your dedication.", "effects": {"yakkai": 1}},
    {"id": 49, "question": "When a seiyuu bends down on stage, reaching for binoculars is a completely natural reaction.", "effects": {"degenerate": 1}},
    {"id": 50, "question": "The main reason I invest in 8x-10x binoculars is to see my oshi's expressions... and other things... up close.", "effects": {"degenerate": 1}},
    {"id": 51, "question": "If my oshi's character gets a swimsuit card or figure, that's the highlight of my entire month.", "effects": {"degenerate": 1}},
    {"id": 52, "question": "I've spent more time analyzing fanservice screenshots of my oshi than actually listening to the music.", "effects": {"degenerate": 1}},
    {"id": 53, "question": "Love Live concerts would be more fun if the crowd adopted 3D idol call culture like gachikoi koujou and 3ren kahen.", "effects": {"yakkai": 1}},
    {"id": 54, "question": "A real fan should be able to explain what they admire about their oshi beyond just looks.", "effects": {"degenerate": -1}},
];
