questions =  [
    {"id": 1, "question": "I view the seiyuu primarily as talented artists and professionals, not as objects for my personal fantasy.", "effects": {"degenerate": -1}},
    {"id": 2, "question": "Fans who make inappropriate sexual comments about the cast on Discord or Twitter should be completely shunned by the community.", "effects": {"degenerate": -1}},
    {"id": 3, "question": "Holding more than one standard electronic penlight to a concert is completely unnecessary and excessive.", "effects": {"yakkai": -1}},
    {"id": 4    , "question": "When a seiyuu bends down on stage, reaching for binoculars is a completely natural reaction.", "effects": {"degenerate": 1}},
    {"id": 5, "question": "Jumping or vigorously waving a penlight to the beat is distracting; fans should just watch the stage quietly.", "effects": {"yakkai": -1}},
    {"id": 6, "question": "I attend lives primarily to appreciate the vocal talents, choreography, and the live band, rather than to glaze at the cast.", "effects": {"degenerate": -1}},
    {"id": 7, "question": "I've spent more time analyzing fanservice screenshots of my oshi than actually listening to the music.", "effects": {"degenerate": 1}},
    {"id": 8, "question": "If my oshi's character gets a swimsuit card or figure, that's the highlight of my entire month.", "effects": {"degenerate": 1}},
    {"id": 9, "question": "Shouting the Standard Mix ('Tiger, Fire, Cyber, Fiber, Diver, Viber, Jyaa Jyaa!') during a Love Live song intro is a great way to hype up the crowd.", "effects": {"yakkai": 1}},
    {"id": 10, "question": "Doing excessive Wotagei movements (like the Thunder Snake or Cyclone) in a cramped arena seat is totally justified if the song goes hard.", "effects": {"yakkai": 1}},
    {"id": 11, "question": "Cracking an entire 25-pack box of UOs over the course of a single concert is normal behavior for a dedicated fan.", "effects": {"yakkai": 1}},
    {"id": 12, "question": "Screaming an idol's name at the top of my lungs while they are trying to do a quiet, emotional MC is completely acceptable.", "effects": {"yakkai": 1}},
    {"id": 13, "question": "Sneaking in a modified, excessively bright penlight that exceeds venue regulations is a great idea to make my oshi notice me from the stage.", "effects": {"yakkai": 1}},
    {"id": 14, "question": "I care more about front-row arena seats to look at the performers' legs than actually hearing the live band and vocals.", "effects": {"degenerate": 1}},
    {"id": 15, "question": "I think it is inappropriate to call out the seiyuu's name or shout \"ganbare\" (do your best) when a seiyuu on stage is crying during an MC segment", "effects": {"yakkai": 1}},
    {"id": 16, "question": "The performers' personal lives are none of my business, and I don't care who they date or associate with off-stage.", "effects": {"degenerate": -1}},
    {"id": 17, "question": "Looping the buppan line to spend my entire monthly paycheck on trading bromides and gacha to complete my shrine is a healthy financial decision.", "effects": {"degenerate": 1}},
    {"id": 18, "question": "If the music fades out into a dead-silent acoustic break, that is the perfect time to yell 'Yeah Taiga!' to get a laugh.", "effects": {"yakkai": 1}},
    {"id": 19, "question": "When a new picture of a seiyuu drops on Discord, typing 'WOOOOOOOAH' is a completely normal and appropriate response.", "effects": {"degenerate": 1}},
    {"id": 20, "question": "I regularly make comments wishing a specific idol would 'step on me' or physically/verbally abuse me.", "effects": {"degenerate": 1}},
    {"id": 21, "question": "It is perfectly fine to closely analyze and make remarks about an idol's specific body parts when discussing them online.", "effects": {"degenerate": 1}},
    {"id": 22, "question": "When discussing a live, the conversation should focus on vocal performance, choreography, and emotional delivery rather than looks.", "effects": {"degenerate": -1}},
    {"id": 23, "question": "Leaving meaningful, constructive comments about a performance is far better than just spamming reaction memes and emojis.", "effects": {"degenerate": -1}},
    {"id": 24, "question": "I would genuinely be happy for a seiyuu if they announced they got married, rather than feeling betrayed or angry.", "effects": {"degenerate": -1}},
    {"id": 25, "question": "Popping a high-brightness Ultra Orange (UO) during a slow, blue-themed ballad is a fine.", "effects": {"yakkai": 1}},
    {"id": 26, "question": "Doing the cyclone (spinning glowsticks in a cartwheel motion above your head) is perfectly fine, even if the song isn't particularly hyped.", "effects": {"yakkai": 1}},
    {"id": 27, "question": "If my aggressive calling or penlight swinging annoys my renban (seat partner), that's their problem, not mine.", "effects": {"yakkai": 1}},
    {"id": 28, "question": "Jumping and getting sweaty at a live is exhausting; I prefer to sit or stand motionless to fully absorb the performance.", "effects": {"yakkai": -1}},
    {"id": 29, "question": "I have a dedicated folder on my phone exclusively for saving screenshots of my oshi's best angles from lives and streams.", "effects": {"degenerate": 1}},
    {"id": 30, "question": "If staff say 'no standing' or 'no jumping', I follow it strictly even if others don’t.", "effects": {"yakkai": -1}},
    {"id": 31, "question": "I coordinate my ita-bag with 30+ badges of the same character and I feel zero shame carrying it in public.", "effects": {"degenerate": 1}},
    {"id": 32, "question": "Being a DD (loving all members equally) is healthier than obsessively fixating on a single oshi.", "effects": {"degenerate": -1}},
    {"id": 33, "question": "Wearing different group/franchise shirt and merchandise to a concert is acceptable and funny.", "effects": {"yakkai": 1}},
    {"id": 34, "question": "I would zentsuu (attend every single day and leg of a tour across Japan) even if it meant skipping work or using all my vacation days.", "effects": {"degenerate": 1}},
    {"id": 35, "question": "I think the whole culture of sending fan letters and gifts to seiyuu is excessive and unnecessary.", "effects": {"yakkai": -1}},
    {"id": 36, "question": "Going to more than one day of the same concert is a waste of money since the setlist is basically the same.", "effects": {"yakkai": -1}},
    {"id": 37, "question": "I leave during the MC sections to use the bathroom or check my phone since nothing important happens.", "effects": {"yakkai": 1}},
    {"id": 38, "question": "I don't bother with the encore calls because the performers are coming back anyway, it's all scripted.", "effects": {"yakkai": -1}},
    {"id": 39, "question": "I sit during the units/seiyuu I don't like since there is not point in cheering.", "effects": {"yakkai": 1}},
    {"id": 40, "question": "I have genuinely cried over a 2D idol's in-universe graduation or disbandment harder than I've cried over real life events.", "effects": {"degenerate": 1}},
    {"id": 41, "question": "I make an effort to reply every single time my oshi posts on social media, no matter how meaningless the post is (e.g. good morning tweets)", "effects": {"degenerate": 1}},
    {"id": 42, "question": "When new fans ask basic questions, I patiently help them instead of gatekeeping or getting annoyed.", "effects": {"yakkai": -1}},
    {"id": 43, "question": "If my seat is at the very back of the arena, I treat it as a free pass to do whatever I want since nobody important can see me.", "effects": {"yakkai": 1}},
    {"id": 44, "question": "I've fallen asleep during a ballad segment at a live and I don't feel bad about it.", "effects": {"yakkai": 1}},
    {"id": 45, "question": "I’d rather under-react than over-react and risk bothering someone nearby.", "effects": {"yakkai": -1}},
    {"id": 46, "question": "I save controversial calls/mixes for karaoke or anikura, not for the actual Love Live venue.", "effects": {"yakkai": -1}},
    {"id": 47, "question": "Breaking UOs randomly is fine—even if the section is doing a calm color and the song isn’t a hype moment.", "effects": {"yakkai": 1}},
    {"id": 48, "question": "I feel second-hand embarrassment when people spam ‘WOOOAAAH’ style reactions with no meaningful comment.", "effects": {"degenerate": -1}},
    {"id": 49, "question": "If a call or chant is frowned upon in Love Live concerts, doing it anyway ‘for the meme’ is still fair game.", "effects": {"yakkai": 1}},
    {"id": 50, "question": "I don't bring UOs to lives because they're wasteful, expensive, and unnecessary.", "effects": {"yakkai": -1}},

];
